server:
  port: 9090

spring:
  datasource:
    dynamic:
      primary: TData
      datasource:
        TData:
          driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
          url: ${DB_URL:jdbc:mysql://localhost:3306/tdata?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&}
          username: ${DB_USERNAME:root}
          password: ${DB_PASSWORD:123456}
#        Others:
#          driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
#          url: ${DB_URL:jdbc:mysql://localhost:3306/qhoa61?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&}
#          username: ${DB_USERNAME:root}
#          password: ${DB_PASSWORD:123456}
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb

#mybatis-plus
#mybatis-plus.config-location=
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

filePath: src\\main\\resources
#filePath=//usr//games//fcTest

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 259200
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
