server:
  port: 9090

spring:
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL:jdbc:mysql://localhost:3306/tdata?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb

#mybatis-plus??
#mybatis-plus.config-location=
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

filePath: src\\main\\resources
#filePath=//usr//games//fcTest